export const notes = [
  {
    agent: "Sarah Johnson",
    date: "2024-03-15",
    summary:
      "Discussed Q1 performance. Exceeding targets in all areas. Planning advanced training for team leadership. Set goal to improve sits-to-sales ratio by 5% next quarter.",
  },
  {
    agent: "Michael Chen",
    date: "2024-03-14",
    summary:
      "Review of client acquisition strategy. Need to focus on follow-up consistency. Identified opportunity to improve scheduling efficiency. Will implement new CRM workflow.",
  },
  {
    agent: "Emily Rodriguez",
    date: "2024-03-13",
    summary:
      "Monthly performance review. Strong conversion rates but needs improvement in initial contact rates. Set up weekly check-ins for next month to monitor progress.",
  },
  {
    agent: "David Kim",
    date: "2024-03-12",
    summary:
      "Career development discussion. Interested in team lead position. Created 90-day action plan focusing on leadership skills and mentoring junior agents.",
  },
  {
    agent: "Sarah Johnson",
    date: "2024-03-10",
    summary:
      "Weekly check-in. Discussed challenges with recent difficult client case. Provided strategies for handling objections. Reviewed successful closes from past week.",
  },
  {
    agent: "Michael Chen",
    date: "2024-03-09",
    summary:
      "Pipeline review. Strong potential in current leads. Discussed time management techniques to improve contact rates. Set daily goals for client touchpoints.",
  },
  {
    agent: "Lisa Thompson",
    date: "2024-03-08",
    summary:
      "Quarterly review. Outstanding performance in AP per sale. Sharing best practices with team. Discussed expansion of territory coverage.",
  },
  {
    agent: "Emily Rodriguez",
    date: "2024-03-07",
    summary:
      "Training follow-up. Successfully implementing new sales techniques. Seeing improvement in conversion rates. Scheduled advanced product training for next week.",
  },
  {
    agent: "David Kim",
    date: "2024-03-06",
    summary:
      "Goal setting session. Established targets for Q2. Focus on increasing average premium per policy. Created action plan for reaching out to existing clients.",
  },
  {
    agent: "Sarah Johnson",
    date: "2024-03-05",
    summary:
      "Strategy meeting. Reviewed success with recent marketing campaign. Planning to scale approach across team. Discussed upcoming product launch preparation.",
  },
  {
    agent: "James Wilson",
    date: "2024-03-15",
    summary:
      "Weekly performance review. Strong improvement in lead conversion. Implementing new follow-up system showing positive results. Discussed expansion of referral network.",
  },
  {
    agent: "Sophie Clark",
    date: "2024-03-14",
    summary:
      "Leadership strategy session. Reviewing team metrics and identifying growth opportunities. Created action plan for improving team's sits-to-sales ratio.",
  },
  {
    agent: "Alex Turner",
    date: "2024-03-13",
    summary:
      "Training assessment. Making good progress with new sales approach. Need to work on objection handling. Scheduled role-play session for next week.",
  },
  {
    agent: "James Wilson",
    date: "2024-03-11",
    summary:
      "Pipeline analysis. Strong potential in current lead pool. Developed strategy for prioritizing high-value prospects. Set new targets for AP per sale.",
  },
  {
    agent: "Sophie Clark",
    date: "2024-03-10",
    summary:
      "Quarterly planning session. Team exceeding conversion targets. Developed new training program for junior agents. Discussed upcoming territory expansion.",
  },
  {
    agent: "Alex Turner",
    date: "2024-03-08",
    summary:
      "Performance check-in. Showing improvement in contact rates. Created personalized script for cold calls. Set daily activity goals for next two weeks.",
  },
  {
    agent: "Emily Rodriguez",
    date: "2024-03-06",
    summary:
      "Development planning. Discussed career progression and leadership opportunities. Created skill development plan focusing on advanced sales techniques.",
  },
  {
    agent: "Maria Garcia",
    date: "2024-03-15",
    summary:
      "Team lead strategy meeting. Reviewing department performance metrics. Implementing new coaching program for underperforming agents. Set Q2 team objectives.",
  },
  {
    agent: "John Anderson",
    date: "2024-03-14",
    summary:
      "Monthly review. Excellent progress in lead conversion rates. Sharing successful closing techniques with team. Discussed upcoming product certification.",
  },
  {
    agent: "Tom Lee",
    date: "2024-03-13",
    summary:
      "Performance optimization session. Analyzing call metrics and conversion funnel. Identified areas for improvement in follow-up process.",
  },
  {
    agent: "Anna White",
    date: "2024-03-12",
    summary:
      "Onboarding progress review. Successfully completing initial training phases. Set up mentoring partnership with senior agent. Created 30-day improvement plan.",
  },
  {
    agent: "Chris Taylor",
    date: "2024-03-11",
    summary:
      "Sales strategy meeting. Reviewing success with new market approach. Developed plan for expanding into new territory. Discussed cross-selling opportunities.",
  },
  {
    agent: "Kelly Brown",
    date: "2024-03-10",
    summary:
      "Quarterly performance review. Meeting most targets but needs improvement in AP per sale. Created action plan for increasing premium values.",
  },
  {
    agent: "Maria Garcia",
    date: "2024-03-09",
    summary:
      "Leadership development session. Discussing team management strategies. Planning implementation of new performance tracking system.",
  },
  {
    agent: "John Anderson",
    date: "2024-03-08",
    summary:
      "Success planning meeting. Strong performance in client retention. Developed strategies for generating referrals. Set new goals for upcoming quarter.",
  },
  {
    agent: "Tom Lee",
    date: "2024-03-07",
    summary:
      "Weekly check-in. Showing consistent improvement in sits-to-sales ratio. Created action plan for reaching President's Club targets.",
  },
  {
    agent: "Anna White",
    date: "2024-03-06",
    summary:
      "Skills assessment. Making progress with sales techniques. Scheduled additional training for complex product lines. Set weekly learning objectives.",
  },
  {
    agent: "Robert Foster",
    date: "2024-03-15",
    summary:
      "Quarterly strategy review. Team showing strong growth in conversion rates. Implementing new training program for lead qualification.",
  },
  {
    agent: "Jennifer Wu",
    date: "2024-03-14",
    summary:
      "Performance review. Excellent progress in client retention. Developed new approach for follow-up calls showing promising results.",
  },
  {
    agent: "Marcus Bennett",
    date: "2024-03-13",
    summary:
      "Weekly check-in. Discussed optimization of cold calling strategy. Set new targets for contact rates and scheduled appointments.",
  },
  {
    agent: "Sophia Patel",
    date: "2024-03-12",
    summary:
      "Monthly review. Strong performance in sales closure. Sharing best practices with team members. Planning territory expansion.",
  },
  {
    agent: "Daniel Park",
    date: "2024-03-15",
    summary:
      "Team leadership meeting. Reviewing Q1 metrics and planning Q2 objectives. Implementing new coaching framework.",
  },
  {
    agent: "Rachel Cohen",
    date: "2024-03-14",
    summary:
      "Success metrics review. Showing consistent improvement in conversion rates. Created action plan for reaching higher AP targets.",
  },
  {
    agent: "Kevin O'Brien",
    date: "2024-03-13",
    summary:
      "Training session follow-up. Successfully implementing new sales techniques. Scheduled advanced product knowledge workshop.",
  },
  {
    agent: "Amanda Torres",
    date: "2024-03-15",
    summary:
      "Department strategy meeting. Analyzing team performance metrics. Planning implementation of new lead distribution system.",
  },
  {
    agent: "Brian Murphy",
    date: "2024-03-14",
    summary:
      "Pipeline review. Strong potential in current leads. Developed strategy for high-value prospect targeting.",
  },
  {
    agent: "Michelle Wong",
    date: "2024-03-13",
    summary:
      "Skill development session. Excellent progress in objection handling. Created personalized improvement plan for Q2.",
  },
  {
    agent: "Ethan Wilson",
    date: "2024-03-15",
    summary:
      "Performance review. Excellent progress in sales metrics. Planning implementation of new lead management system.",
  },
  {
    agent: "Mia Thompson",
    date: "2024-03-14",
    summary:
      "Development session. Successfully completing advanced training modules. Set new targets for Q2 performance.",
  },
  {
    agent: "Jason Wright",
    date: "2024-03-15",
    summary:
      "Monthly performance review. Strong results in lead conversion. Implementing new follow-up strategy for improved contact rates.",
  },
  {
    agent: "Emma Davis",
    date: "2024-03-14",
    summary:
      "Weekly check-in. Discussed optimization of sales process. Set new goals for AP per sale improvement.",
  },
  {
    agent: "Ryan Cooper",
    date: "2024-03-15",
    summary:
      "Strategy session. Excellent progress in client acquisition. Developed new approach for high-value leads.",
  },
  {
    agent: "Olivia Martinez",
    date: "2024-03-14",
    summary:
      "Training review. Successfully implementing advanced sales techniques. Planning territory expansion.",
  },
  {
    agent: "Lucas Kim",
    date: "2024-03-15",
    summary:
      "Performance optimization meeting. Strong improvement in conversion metrics. Created action plan for Q2 targets.",
  },
  {
    agent: "Isabella Santos",
    date: "2024-03-14",
    summary:
      "Development planning. Discussed career growth opportunities. Set up mentoring program with senior agents.",
  },
  {
    agent: "Nathan Chen",
    date: "2024-03-15",
    summary:
      "Weekly review. Strong performance in lead qualification. Implementing new client retention strategies.",
  },
  {
    agent: "Sophia Lee",
    date: "2024-03-14",
    summary:
      "Success metrics analysis. Excellent progress in sales closure rates. Planning advanced product training.",
  },
  {
    agent: "William Taylor",
    date: "2024-03-15",
    summary:
      "Strategy meeting. Reviewing team performance metrics. Created action plan for conversion rate improvement.",
  },
  {
    agent: "Ava Rodriguez",
    date: "2024-03-14",
    summary:
      "Quarterly planning session. Strong results in client acquisition. Developing new approach for referral generation.",
  },
  {
    agent: "Ethan Wilson",
    date: "2024-03-15",
    summary:
      "Performance review. Excellent progress in sales metrics. Planning implementation of new lead management system.",
  },
  {
    agent: "Mia Thompson",
    date: "2024-03-14",
    summary:
      "Development session. Successfully completing advanced training modules. Set new targets for Q2 performance.",
  },
  {
    agent: "Victoria Chang",
    date: "2024-03-15",
    summary:
      "Team leadership review. Excellent progress in team development. Implementing new coaching strategies for performance optimization.",
  },
  {
    agent: "Adrian Foster",
    date: "2024-03-14",
    summary:
      "Monthly performance check-in. Strong improvement in lead conversion rates. Created action plan for Q2 goals.",
  },
  {
    agent: "Nina Patel",
    date: "2024-03-13",
    summary:
      "Strategy session. Successfully implementing new sales approach. Planning expansion of client portfolio.",
  },
  {
    agent: "Jordan Hayes",
    date: "2024-03-12",
    summary:
      "Development review. Excellent progress in sales techniques. Set new targets for advanced certification.",
  },
  {
    agent: "Cameron Ross",
    date: "2024-03-11",
    summary:
      "Weekly check-in. Strong performance in client retention. Developing new approach for high-value accounts.",
  },
  {
    agent: "Morgan Silva",
    date: "2024-03-10",
    summary:
      "Success metrics analysis. Showing consistent improvement in all KPIs. Created action plan for reaching President's Club.",
  },
  {
    agent: "Taylor Reed",
    date: "2024-03-09",
    summary:
      "Training assessment. Making excellent progress with new sales methodology. Scheduled advanced product training.",
  },
  {
    agent: "Samuel Park",
    date: "2024-03-15",
    summary:
      "Leadership strategy meeting. Reviewing team performance and implementing new coaching framework.",
  },
  {
    agent: "Riley Morgan",
    date: "2024-03-14",
    summary:
      "Quarterly review. Strong results in lead qualification. Planning implementation of new follow-up system.",
  },
  {
    agent: "Casey Zhang",
    date: "2024-03-13",
    summary:
      "Performance optimization session. Excellent progress in conversion metrics. Set new goals for Q2.",
  },
  {
    agent: "Drew Campbell",
    date: "2024-03-12",
    summary:
      "Development planning. Successfully implementing advanced sales strategies. Created action plan for skill enhancement.",
  },
  {
    agent: "Avery Nguyen",
    date: "2024-03-11",
    summary:
      "Weekly progress review. Strong improvement in client engagement. Developing new approach for referral generation.",
  },
  {
    agent: "Jamie Collins",
    date: "2024-03-10",
    summary:
      "Success metrics check-in. Consistently meeting performance targets. Planning territory expansion strategy.",
  },
];

export type Metrics = {
  leads: number;
  calls: number;
  contacts: number;
  scheduled: number;
  sits: number;
  sales: number;
  ap: number;
  conversion: number;
  ratios: {
    leadToContact: number;
    leadToScheduled: number;
    leadToSits: number;
    leadToSales: number;
    apPerLead: number;
    contactToScheduled: number;
    contactToSits: number;
    callsToContact: number;
    callsToScheduled: number;
    callsToSits: number;
    callsToSales: number;
    apPerCall: number;
    contactToSales: number;
    apPerContact: number;
    scheduledToSits: number;
    sitsToSales: number;
    apPerSit: number;
    apPerSale: number;
  };
};

export const teamAgents = {
  "Alpha Team": [
    {
      name: "Sarah Johnson",
      role: "Manager",
      metrics: {
        leads: 45,
        calls: 38,
        contacts: 32,
        scheduled: 15,
        sits: 12,
        sales: 8,
        ap: 2400,
        conversion: 67,
        ratios: {
          leadToContact: 71,
          leadToScheduled: 33,
          leadToSits: 27,
          leadToSales: 18,
          apPerLead: 53,
          contactToScheduled: 47,
          contactToSits: 38,
          callsToContact: 84,
          callsToScheduled: 39,
          callsToSits: 32,
          callsToSales: 21,
          apPerCall: 63,
          contactToSales: 25,
          apPerContact: 75,
          scheduledToSits: 80,
          sitsToSales: 67,
          apPerSit: 200,
          apPerSale: 300,
        },
      },
    },
    {
      name: "Michael Chen",
      role: "Agent",
      metrics: {
        leads: 38,
        calls: 32,
        contacts: 28,
        scheduled: 12,
        sits: 10,
        sales: 6,
        ap: 1800,
        conversion: 40,
        ratios: {
          leadToContact: 74,
          leadToScheduled: 32,
          leadToSits: 26,
          leadToSales: 16,
          apPerLead: 47,
          contactToScheduled: 43,
          contactToSits: 36,
          callsToContact: 88,
          callsToScheduled: 38,
          callsToSits: 31,
          callsToSales: 19,
          apPerCall: 56,
          contactToSales: 21,
          apPerContact: 64,
          scheduledToSits: 83,
          sitsToSales: 60,
          apPerSit: 180,
          apPerSale: 300,
        },
      },
    },
    {
      name: "Lisa Thompson",
      role: "Agent",
      metrics: {
        leads: 42,
        calls: 36,
        contacts: 30,
        scheduled: 14,
        sits: 11,
        sales: 7,
        ap: 2100,
        conversion: 63,
        ratios: {
          leadToContact: 71,
          leadToScheduled: 33,
          leadToSits: 26,
          leadToSales: 17,
          apPerLead: 50,
          contactToScheduled: 47,
          contactToSits: 37,
          callsToContact: 83,
          callsToScheduled: 39,
          callsToSits: 31,
          callsToSales: 19,
          apPerCall: 58,
          contactToSales: 23,
          apPerContact: 70,
          scheduledToSits: 79,
          sitsToSales: 64,
          apPerSit: 191,
          apPerSale: 300,
        },
      },
    },
    {
      name: "David Kim",
      role: "Manager",
      metrics: {
        leads: 48,
        calls: 40,
        contacts: 34,
        scheduled: 16,
        sits: 13,
        sales: 9,
        ap: 2700,
        conversion: 69,
        ratios: {
          leadToContact: 71,
          leadToScheduled: 33,
          leadToSits: 27,
          leadToSales: 19,
          apPerLead: 56,
          contactToScheduled: 47,
          contactToSits: 38,
          callsToContact: 85,
          callsToScheduled: 40,
          callsToSits: 33,
          callsToSales: 23,
          apPerCall: 68,
          contactToSales: 26,
          apPerContact: 79,
          scheduledToSits: 81,
          sitsToSales: 69,
          apPerSit: 208,
          apPerSale: 300,
        },
      },
    },
    {
      name: "Rachel Martinez",
      role: "Agent",
      metrics: {
        leads: 40,
        calls: 34,
        contacts: 29,
        scheduled: 13,
        sits: 10,
        sales: 6,
        ap: 1800,
        conversion: 60,
        ratios: {
          leadToContact: 73,
          leadToScheduled: 33,
          leadToSits: 25,
          leadToSales: 15,
          apPerLead: 45,
          contactToScheduled: 45,
          contactToSits: 34,
          callsToContact: 85,
          callsToScheduled: 38,
          callsToSits: 29,
          callsToSales: 18,
          apPerCall: 53,
          contactToSales: 21,
          apPerContact: 62,
          scheduledToSits: 77,
          sitsToSales: 60,
          apPerSit: 180,
          apPerSale: 300,
        },
      },
    },
    {
      name: "Jason Wright",
      role: "Agent",
      metrics: {
        leads: 43,
        calls: 36,
        contacts: 31,
        scheduled: 14,
        sits: 11,
        sales: 7,
        ap: 2100,
        conversion: 65,
        ratios: {
          leadToContact: 72,
          leadToScheduled: 33,
          leadToSits: 26,
          leadToSales: 16,
          apPerLead: 49,
          contactToScheduled: 45,
          contactToSits: 35,
          callsToContact: 86,
          callsToScheduled: 39,
          callsToSits: 31,
          callsToSales: 19,
          apPerCall: 58,
          contactToSales: 23,
          apPerContact: 68,
          scheduledToSits: 79,
          sitsToSales: 64,
          apPerSit: 191,
          apPerSale: 300,
        },
      },
    },
    {
      name: "Emma Davis",
      role: "Agent",
      metrics: {
        leads: 41,
        calls: 35,
        contacts: 30,
        scheduled: 14,
        sits: 11,
        sales: 7,
        ap: 2100,
        conversion: 63,
        ratios: {
          leadToContact: 73,
          leadToScheduled: 34,
          leadToSits: 27,
          leadToSales: 17,
          apPerLead: 51,
          contactToScheduled: 47,
          contactToSits: 37,
          callsToContact: 86,
          callsToScheduled: 40,
          callsToSits: 31,
          callsToSales: 20,
          apPerCall: 60,
          contactToSales: 23,
          apPerContact: 70,
          scheduledToSits: 79,
          sitsToSales: 64,
          apPerSit: 191,
          apPerSale: 300,
        },
      },
    },
  ],
  "Beta Team": [
    {
      name: "James Wilson",
      role: "Agent",
      metrics: {
        leads: 41,
        calls: 35,
        contacts: 30,
        scheduled: 16,
        sits: 12,
        sales: 7,
        ap: 2100,
        conversion: 70,
        ratios: {
          leadToContact: 73,
          leadToScheduled: 39,
          leadToSits: 29,
          leadToSales: 17,
          apPerLead: 51,
          contactToScheduled: 53,
          contactToSits: 40,
          callsToContact: 86,
          callsToScheduled: 46,
          callsToSits: 34,
          callsToSales: 20,
          apPerCall: 60,
          contactToSales: 23,
          apPerContact: 70,
          scheduledToSits: 75,
          sitsToSales: 58,
          apPerSit: 175,
          apPerSale: 300,
        },
      },
    },
    {
      name: "Emily Rodriguez",
      role: "Agent",
      metrics: {
        leads: 52,
        calls: 44,
        contacts: 36,
        scheduled: 14,
        sits: 8,
        sales: 4,
        ap: 1200,
        conversion: 50,
        ratios: {
          leadToContact: 69,
          leadToScheduled: 27,
          leadToSits: 15,
          leadToSales: 8,
          apPerLead: 23,
          contactToScheduled: 39,
          contactToSits: 22,
          callsToContact: 82,
          callsToScheduled: 32,
          callsToSits: 18,
          callsToSales: 9,
          apPerCall: 27,
          contactToSales: 11,
          apPerContact: 33,
          scheduledToSits: 57,
          sitsToSales: 50,
          apPerSit: 150,
          apPerSale: 300,
        },
      },
    },
    {
      name: "Alex Turner",
      role: "Agent",
      metrics: {
        leads: 39,
        calls: 33,
        contacts: 28,
        scheduled: 13,
        sits: 9,
        sales: 5,
        ap: 1500,
        conversion: 55,
        ratios: {
          leadToContact: 72,
          leadToScheduled: 33,
          leadToSits: 23,
          leadToSales: 13,
          apPerLead: 38,
          contactToScheduled: 46,
          contactToSits: 32,
          callsToContact: 85,
          callsToScheduled: 39,
          callsToSits: 27,
          callsToSales: 15,
          apPerCall: 45,
          contactToSales: 18,
          apPerContact: 54,
          scheduledToSits: 69,
          sitsToSales: 56,
          apPerSit: 167,
          apPerSale: 300,
        },
      },
    },
    {
      name: "Sophie Clark",
      role: "Manager",
      metrics: {
        leads: 44,
        calls: 37,
        contacts: 31,
        scheduled: 15,
        sits: 11,
        sales: 7,
        ap: 2100,
        conversion: 64,
        ratios: {
          leadToContact: 70,
          leadToScheduled: 34,
          leadToSits: 25,
          leadToSales: 16,
          apPerLead: 48,
          contactToScheduled: 48,
          contactToSits: 35,
          callsToContact: 84,
          callsToScheduled: 41,
          callsToSits: 30,
          callsToSales: 19,
          apPerCall: 57,
          contactToSales: 23,
          apPerContact: 68,
          scheduledToSits: 73,
          sitsToSales: 64,
          apPerSit: 191,
          apPerSale: 300,
        },
      },
    },
    {
      name: "Ryan Cooper",
      role: "Agent",
      metrics: {
        leads: 44,
        calls: 37,
        contacts: 32,
        scheduled: 15,
        sits: 12,
        sales: 8,
        ap: 2400,
        conversion: 67,
        ratios: {
          leadToContact: 73,
          leadToScheduled: 34,
          leadToSits: 27,
          leadToSales: 18,
          apPerLead: 55,
          contactToScheduled: 47,
          contactToSits: 38,
          callsToContact: 86,
          callsToScheduled: 41,
          callsToSits: 32,
          callsToSales: 22,
          apPerCall: 65,
          contactToSales: 25,
          apPerContact: 75,
          scheduledToSits: 80,
          sitsToSales: 67,
          apPerSit: 200,
          apPerSale: 300,
        },
      },
    },
    {
      name: "Olivia Martinez",
      role: "Agent",
      metrics: {
        leads: 42,
        calls: 36,
        contacts: 31,
        scheduled: 14,
        sits: 11,
        sales: 7,
        ap: 2100,
        conversion: 64,
        ratios: {
          leadToContact: 74,
          leadToScheduled: 33,
          leadToSits: 26,
          leadToSales: 17,
          apPerLead: 50,
          contactToScheduled: 45,
          contactToSits: 35,
          callsToContact: 86,
          callsToScheduled: 39,
          callsToSits: 31,
          callsToSales: 19,
          apPerCall: 58,
          contactToSales: 23,
          apPerContact: 68,
          scheduledToSits: 79,
          sitsToSales: 64,
          apPerSit: 191,
          apPerSale: 300,
        },
      },
    },
  ],
  "Gamma Team": [
    {
      name: "John Anderson",
      role: "Agent",
      metrics: {
        leads: 43,
        calls: 36,
        contacts: 31,
        scheduled: 14,
        sits: 10,
        sales: 6,
        ap: 1800,
        conversion: 60,
        ratios: {
          leadToContact: 72,
          leadToScheduled: 33,
          leadToSits: 23,
          leadToSales: 14,
          apPerLead: 42,
          contactToScheduled: 45,
          contactToSits: 32,
          callsToContact: 86,
          callsToScheduled: 39,
          callsToSits: 28,
          callsToSales: 17,
          apPerCall: 50,
          contactToSales: 19,
          apPerContact: 58,
          scheduledToSits: 71,
          sitsToSales: 60,
          apPerSit: 180,
          apPerSale: 300,
        },
      },
    },
    {
      name: "Maria Garcia",
      role: "Manager",
      metrics: {
        leads: 47,
        calls: 40,
        contacts: 34,
        scheduled: 16,
        sits: 12,
        sales: 8,
        ap: 2400,
        conversion: 67,
        ratios: {
          leadToContact: 72,
          leadToScheduled: 34,
          leadToSits: 26,
          leadToSales: 17,
          apPerLead: 51,
          contactToScheduled: 47,
          contactToSits: 35,
          callsToContact: 85,
          callsToScheduled: 40,
          callsToSits: 30,
          callsToSales: 20,
          apPerCall: 60,
          contactToSales: 24,
          apPerContact: 71,
          scheduledToSits: 75,
          sitsToSales: 67,
          apPerSit: 200,
          apPerSale: 300,
        },
      },
    },
    {
      name: "Tom Lee",
      role: "Agent",
      metrics: {
        leads: 40,
        calls: 34,
        contacts: 29,
        scheduled: 13,
        sits: 9,
        sales: 5,
        ap: 1500,
        conversion: 56,
        ratios: {
          leadToContact: 73,
          leadToScheduled: 33,
          leadToSits: 23,
          leadToSales: 13,
          apPerLead: 38,
          contactToScheduled: 45,
          contactToSits: 31,
          callsToContact: 85,
          callsToScheduled: 38,
          callsToSits: 26,
          callsToSales: 15,
          apPerCall: 44,
          contactToSales: 17,
          apPerContact: 52,
          scheduledToSits: 69,
          sitsToSales: 56,
          apPerSit: 167,
          apPerSale: 300,
        },
      },
    },
    {
      name: "Anna White",
      role: "Agent",
      metrics: {
        leads: 38,
        calls: 32,
        contacts: 27,
        scheduled: 12,
        sits: 8,
        sales: 4,
        ap: 1200,
        conversion: 50,
        ratios: {
          leadToContact: 71,
          leadToScheduled: 32,
          leadToSits: 21,
          leadToSales: 11,
          apPerLead: 32,
          contactToScheduled: 44,
          contactToSits: 30,
          callsToContact: 84,
          callsToScheduled: 38,
          callsToSits: 25,
          callsToSales: 13,
          apPerCall: 38,
          contactToSales: 15,
          apPerContact: 44,
          scheduledToSits: 67,
          sitsToSales: 50,
          apPerSit: 150,
          apPerSale: 300,
        },
      },
    },
    {
      name: "Chris Taylor",
      role: "Agent",
      metrics: {
        leads: 41,
        calls: 35,
        contacts: 30,
        scheduled: 14,
        sits: 10,
        sales: 6,
        ap: 1800,
        conversion: 60,
        ratios: {
          leadToContact: 73,
          leadToScheduled: 34,
          leadToSits: 24,
          leadToSales: 15,
          apPerLead: 44,
          contactToScheduled: 47,
          contactToSits: 33,
          callsToContact: 86,
          callsToScheduled: 40,
          callsToSits: 29,
          callsToSales: 17,
          apPerCall: 51,
          contactToSales: 20,
          apPerContact: 60,
          scheduledToSits: 71,
          sitsToSales: 60,
          apPerSit: 180,
          apPerSale: 300,
        },
      },
    },
    {
      name: "Kelly Brown",
      role: "Agent",
      metrics: {
        leads: 39,
        calls: 33,
        contacts: 28,
        scheduled: 13,
        sits: 9,
        sales: 5,
        ap: 1500,
        conversion: 56,
        ratios: {
          leadToContact: 72,
          leadToScheduled: 33,
          leadToSits: 23,
          leadToSales: 13,
          apPerLead: 38,
          contactToScheduled: 46,
          contactToSits: 32,
          callsToContact: 85,
          callsToScheduled: 39,
          callsToSits: 27,
          callsToSales: 15,
          apPerCall: 45,
          contactToSales: 18,
          apPerContact: 54,
          scheduledToSits: 69,
          sitsToSales: 56,
          apPerSit: 167,
          apPerSale: 300,
        },
      },
    },
    {
      name: "Lucas Kim",
      role: "Agent",
      metrics: {
        leads: 45,
        calls: 38,
        contacts: 32,
        scheduled: 15,
        sits: 12,
        sales: 8,
        ap: 2400,
        conversion: 67,
        ratios: {
          leadToContact: 71,
          leadToScheduled: 33,
          leadToSits: 27,
          leadToSales: 18,
          apPerLead: 53,
          contactToScheduled: 47,
          contactToSits: 38,
          callsToContact: 84,
          callsToScheduled: 39,
          callsToSits: 32,
          callsToSales: 21,
          apPerCall: 63,
          contactToSales: 25,
          apPerContact: 75,
          scheduledToSits: 80,
          sitsToSales: 67,
          apPerSit: 200,
          apPerSale: 300,
        },
      },
    },
    {
      name: "Isabella Santos",
      role: "Agent",
      metrics: {
        leads: 41,
        calls: 35,
        contacts: 30,
        scheduled: 14,
        sits: 11,
        sales: 7,
        ap: 2100,
        conversion: 64,
        ratios: {
          leadToContact: 73,
          leadToScheduled: 34,
          leadToSits: 27,
          leadToSales: 17,
          apPerLead: 51,
          contactToScheduled: 47,
          contactToSits: 37,
          callsToContact: 86,
          callsToScheduled: 40,
          callsToSits: 31,
          callsToSales: 20,
          apPerCall: 60,
          contactToSales: 23,
          apPerContact: 70,
          scheduledToSits: 79,
          sitsToSales: 64,
          apPerSit: 191,
          apPerSale: 300,
        },
      },
    },
  ],
  "Delta Team": [
    {
      name: "Robert Foster",
      role: "Manager",
      metrics: {
        leads: 46,
        calls: 39,
        contacts: 33,
        scheduled: 15,
        sits: 12,
        sales: 8,
        ap: 2400,
        conversion: 66,
        ratios: {
          leadToContact: 72,
          leadToScheduled: 33,
          leadToSits: 26,
          leadToSales: 17,
          apPerLead: 52,
          contactToScheduled: 45,
          contactToSits: 36,
          callsToContact: 85,
          callsToScheduled: 38,
          callsToSits: 31,
          callsToSales: 21,
          apPerCall: 62,
          contactToSales: 24,
          apPerContact: 73,
          scheduledToSits: 80,
          sitsToSales: 67,
          apPerSit: 200,
          apPerSale: 300,
        },
      },
    },
    {
      name: "Jennifer Wu",
      role: "Agent",
      metrics: {
        leads: 42,
        calls: 36,
        contacts: 31,
        scheduled: 14,
        sits: 11,
        sales: 7,
        ap: 2100,
        conversion: 64,
        ratios: {
          leadToContact: 74,
          leadToScheduled: 33,
          leadToSits: 26,
          leadToSales: 17,
          apPerLead: 50,
          contactToScheduled: 45,
          contactToSits: 35,
          callsToContact: 86,
          callsToScheduled: 39,
          callsToSits: 31,
          callsToSales: 19,
          apPerCall: 58,
          contactToSales: 23,
          apPerContact: 68,
          scheduledToSits: 79,
          sitsToSales: 64,
          apPerSit: 191,
          apPerSale: 300,
        },
      },
    },
    {
      name: "Marcus Bennett",
      role: "Agent",
      metrics: {
        leads: 39,
        calls: 33,
        contacts: 28,
        scheduled: 13,
        sits: 10,
        sales: 6,
        ap: 1800,
        conversion: 60,
        ratios: {
          leadToContact: 72,
          leadToScheduled: 33,
          leadToSits: 26,
          leadToSales: 15,
          apPerLead: 46,
          contactToScheduled: 46,
          contactToSits: 36,
          callsToContact: 85,
          callsToScheduled: 39,
          callsToSits: 30,
          callsToSales: 18,
          apPerCall: 55,
          contactToSales: 21,
          apPerContact: 64,
          scheduledToSits: 77,
          sitsToSales: 60,
          apPerSit: 180,
          apPerSale: 300,
        },
      },
    },
    {
      name: "Sophia Patel",
      role: "Agent",
      metrics: {
        leads: 44,
        calls: 37,
        contacts: 32,
        scheduled: 15,
        sits: 12,
        sales: 8,
        ap: 2400,
        conversion: 67,
        ratios: {
          leadToContact: 73,
          leadToScheduled: 34,
          leadToSits: 27,
          leadToSales: 18,
          apPerLead: 55,
          contactToScheduled: 47,
          contactToSits: 38,
          callsToContact: 86,
          callsToScheduled: 41,
          callsToSits: 32,
          callsToSales: 22,
          apPerCall: 65,
          contactToSales: 25,
          apPerContact: 75,
          scheduledToSits: 80,
          sitsToSales: 67,
          apPerSit: 200,
          apPerSale: 300,
        },
      },
    },
    {
      name: "Nathan Chen",
      role: "Agent",
      metrics: {
        leads: 43,
        calls: 37,
        contacts: 31,
        scheduled: 14,
        sits: 11,
        sales: 7,
        ap: 2100,
        conversion: 63,
        ratios: {
          leadToContact: 72,
          leadToScheduled: 33,
          leadToSits: 26,
          leadToSales: 16,
          apPerLead: 49,
          contactToScheduled: 45,
          contactToSits: 35,
          callsToContact: 84,
          callsToScheduled: 38,
          callsToSits: 30,
          callsToSales: 19,
          apPerCall: 57,
          contactToSales: 23,
          apPerContact: 68,
          scheduledToSits: 79,
          sitsToSales: 64,
          apPerSit: 191,
          apPerSale: 300,
        },
      },
    },
    {
      name: "Sophia Lee",
      role: "Agent",
      metrics: {
        leads: 44,
        calls: 37,
        contacts: 32,
        scheduled: 15,
        sits: 12,
        sales: 8,
        ap: 2400,
        conversion: 67,
        ratios: {
          leadToContact: 73,
          leadToScheduled: 34,
          leadToSits: 27,
          leadToSales: 18,
          apPerLead: 55,
          contactToScheduled: 47,
          contactToSits: 38,
          callsToContact: 86,
          callsToScheduled: 41,
          callsToSits: 32,
          callsToSales: 22,
          apPerCall: 65,
          contactToSales: 25,
          apPerContact: 75,
          scheduledToSits: 80,
          sitsToSales: 67,
          apPerSit: 200,
          apPerSale: 300,
        },
      },
    },
  ],
  "Epsilon Team": [
    {
      name: "Daniel Park",
      role: "Manager",
      metrics: {
        leads: 48,
        calls: 41,
        contacts: 35,
        scheduled: 16,
        sits: 13,
        sales: 9,
        ap: 2700,
        conversion: 69,
        ratios: {
          leadToContact: 73,
          leadToScheduled: 33,
          leadToSits: 27,
          leadToSales: 19,
          apPerLead: 56,
          contactToScheduled: 46,
          contactToSits: 37,
          callsToContact: 85,
          callsToScheduled: 39,
          callsToSits: 32,
          callsToSales: 22,
          apPerCall: 66,
          contactToSales: 26,
          apPerContact: 77,
          scheduledToSits: 81,
          sitsToSales: 69,
          apPerSit: 208,
          apPerSale: 300,
        },
      },
    },
    {
      name: "Rachel Cohen",
      role: "Agent",
      metrics: {
        leads: 41,
        calls: 35,
        contacts: 30,
        scheduled: 14,
        sits: 11,
        sales: 7,
        ap: 2100,
        conversion: 64,
        ratios: {
          leadToContact: 73,
          leadToScheduled: 34,
          leadToSits: 27,
          leadToSales: 17,
          apPerLead: 51,
          contactToScheduled: 47,
          contactToSits: 37,
          callsToContact: 86,
          callsToScheduled: 40,
          callsToSits: 31,
          callsToSales: 20,
          apPerCall: 60,
          contactToSales: 23,
          apPerContact: 70,
          scheduledToSits: 79,
          sitsToSales: 64,
          apPerSit: 191,
          apPerSale: 300,
        },
      },
    },
    {
      name: "Kevin O'Brien",
      role: "Agent",
      metrics: {
        leads: 43,
        calls: 37,
        contacts: 31,
        scheduled: 14,
        sits: 11,
        sales: 7,
        ap: 2100,
        conversion: 63,
        ratios: {
          leadToContact: 72,
          leadToScheduled: 33,
          leadToSits: 26,
          leadToSales: 16,
          apPerLead: 49,
          contactToScheduled: 45,
          contactToSits: 35,
          callsToContact: 84,
          callsToScheduled: 38,
          callsToSits: 30,
          callsToSales: 19,
          apPerCall: 57,
          contactToSales: 23,
          apPerContact: 68,
          scheduledToSits: 79,
          sitsToSales: 64,
          apPerSit: 191,
          apPerSale: 300,
        },
      },
    },
    {
      name: "William Taylor",
      role: "Agent",
      metrics: {
        leads: 42,
        calls: 36,
        contacts: 31,
        scheduled: 14,
        sits: 11,
        sales: 7,
        ap: 2100,
        conversion: 64,
        ratios: {
          leadToContact: 74,
          leadToScheduled: 33,
          leadToSits: 26,
          leadToSales: 17,
          apPerLead: 50,
          contactToScheduled: 45,
          contactToSits: 35,
          callsToContact: 86,
          callsToScheduled: 39,
          callsToSits: 31,
          callsToSales: 19,
          apPerCall: 58,
          contactToSales: 23,
          apPerContact: 68,
          scheduledToSits: 79,
          sitsToSales: 64,
          apPerSit: 191,
          apPerSale: 300,
        },
      },
    },
    {
      name: "Ava Rodriguez",
      role: "Agent",
      metrics: {
        leads: 45,
        calls: 38,
        contacts: 32,
        scheduled: 15,
        sits: 12,
        sales: 8,
        ap: 2400,
        conversion: 67,
        ratios: {
          leadToContact: 71,
          leadToScheduled: 33,
          leadToSits: 27,
          leadToSales: 18,
          apPerLead: 53,
          contactToScheduled: 47,
          contactToSits: 38,
          callsToContact: 84,
          callsToScheduled: 39,
          callsToSits: 32,
          callsToSales: 21,
          apPerCall: 63,
          contactToSales: 25,
          apPerContact: 75,
          scheduledToSits: 80,
          sitsToSales: 67,
          apPerSit: 200,
          apPerSale: 300,
        },
      },
    },
  ],
  "Zeta Team": [
    {
      name: "Amanda Torres",
      role: "Manager",
      metrics: {
        leads: 45,
        calls: 38,
        contacts: 32,
        scheduled: 15,
        sits: 12,
        sales: 8,
        ap: 2400,
        conversion: 67,
        ratios: {
          leadToContact: 71,
          leadToScheduled: 33,
          leadToSits: 27,
          leadToSales: 18,
          apPerLead: 53,
          contactToScheduled: 47,
          contactToSits: 38,
          callsToContact: 84,
          callsToScheduled: 39,
          callsToSits: 32,
          callsToSales: 21,
          apPerCall: 63,
          contactToSales: 25,
          apPerContact: 75,
          scheduledToSits: 80,
          sitsToSales: 67,
          apPerSit: 200,
          apPerSale: 300,
        },
      },
    },
    {
      name: "Brian Murphy",
      role: "Agent",
      metrics: {
        leads: 40,
        calls: 34,
        contacts: 29,
        scheduled: 13,
        sits: 10,
        sales: 6,
        ap: 1800,
        conversion: 60,
        ratios: {
          leadToContact: 73,
          leadToScheduled: 33,
          leadToSits: 25,
          leadToSales: 15,
          apPerLead: 45,
          contactToScheduled: 45,
          contactToSits: 34,
          callsToContact: 85,
          callsToScheduled: 38,
          callsToSits: 29,
          callsToSales: 18,
          apPerCall: 53,
          contactToSales: 21,
          apPerContact: 62,
          scheduledToSits: 77,
          sitsToSales: 60,
          apPerSit: 180,
          apPerSale: 300,
        },
      },
    },
    {
      name: "Michelle Wong",
      role: "Agent",
      metrics: {
        leads: 42,
        calls: 36,
        contacts: 30,
        scheduled: 14,
        sits: 11,
        sales: 7,
        ap: 2100,
        conversion: 64,
        ratios: {
          leadToContact: 71,
          leadToScheduled: 33,
          leadToSits: 26,
          leadToSales: 17,
          apPerLead: 50,
          contactToScheduled: 47,
          contactToSits: 37,
          callsToContact: 83,
          callsToScheduled: 39,
          callsToSits: 31,
          callsToSales: 19,
          apPerCall: 58,
          contactToSales: 23,
          apPerContact: 70,
          scheduledToSits: 79,
          sitsToSales: 64,
          apPerSit: 191,
          apPerSale: 300,
        },
      },
    },
    {
      name: "Ethan Wilson",
      role: "Agent",
      metrics: {
        leads: 43,
        calls: 36,
        contacts: 31,
        scheduled: 14,
        sits: 11,
        sales: 7,
        ap: 2100,
        conversion: 65,
        ratios: {
          leadToContact: 72,
          leadToScheduled: 33,
          leadToSits: 26,
          leadToSales: 16,
          apPerLead: 49,
          contactToScheduled: 45,
          contactToSits: 35,
          callsToContact: 86,
          callsToScheduled: 39,
          callsToSits: 31,
          callsToSales: 19,
          apPerCall: 58,
          contactToSales: 23,
          apPerContact: 68,
          scheduledToSits: 79,
          sitsToSales: 64,
          apPerSit: 191,
          apPerSale: 300,
        },
      },
    },
    {
      name: "Mia Thompson",
      role: "Agent",
      metrics: {
        leads: 41,
        calls: 35,
        contacts: 30,
        scheduled: 14,
        sits: 11,
        sales: 7,
        ap: 2100,
        conversion: 63,
        ratios: {
          leadToContact: 73,
          leadToScheduled: 34,
          leadToSits: 27,
          leadToSales: 17,
          apPerLead: 51,
          contactToScheduled: 47,
          contactToSits: 37,
          callsToContact: 86,
          callsToScheduled: 40,
          callsToSits: 31,
          callsToSales: 20,
          apPerCall: 60,
          contactToSales: 23,
          apPerContact: 70,
          scheduledToSits: 79,
          sitsToSales: 64,
          apPerSit: 191,
          apPerSale: 300,
        },
      },
    },
  ],
  "Theta Team": [
    {
      name: "Victoria Chang",
      role: "Manager",
      metrics: {
        leads: 46,
        calls: 39,
        contacts: 33,
        scheduled: 15,
        sits: 12,
        sales: 8,
        ap: 2400,
        conversion: 68,
        ratios: {
          leadToContact: 72,
          leadToScheduled: 33,
          leadToSits: 26,
          leadToSales: 17,
          apPerLead: 52,
          contactToScheduled: 45,
          contactToSits: 36,
          callsToContact: 85,
          callsToScheduled: 38,
          callsToSits: 31,
          callsToSales: 21,
          apPerCall: 62,
          contactToSales: 24,
          apPerContact: 73,
          scheduledToSits: 80,
          sitsToSales: 67,
          apPerSit: 200,
          apPerSale: 300,
        },
      },
    },
    {
      name: "Adrian Foster",
      role: "Agent",
      metrics: {
        leads: 43,
        calls: 36,
        contacts: 31,
        scheduled: 14,
        sits: 11,
        sales: 7,
        ap: 2100,
        conversion: 65,
        ratios: {
          leadToContact: 72,
          leadToScheduled: 33,
          leadToSits: 26,
          leadToSales: 16,
          apPerLead: 49,
          contactToScheduled: 45,
          contactToSits: 35,
          callsToContact: 86,
          callsToScheduled: 39,
          callsToSits: 31,
          callsToSales: 19,
          apPerCall: 58,
          contactToSales: 23,
          apPerContact: 68,
          scheduledToSits: 79,
          sitsToSales: 64,
          apPerSit: 191,
          apPerSale: 300,
        },
      },
    },
    {
      name: "Nina Patel",
      role: "Agent",
      metrics: {
        leads: 44,
        calls: 37,
        contacts: 32,
        scheduled: 15,
        sits: 12,
        sales: 8,
        ap: 2400,
        conversion: 67,
        ratios: {
          leadToContact: 73,
          leadToScheduled: 34,
          leadToSits: 27,
          leadToSales: 18,
          apPerLead: 55,
          contactToScheduled: 47,
          contactToSits: 38,
          callsToContact: 86,
          callsToScheduled: 41,
          callsToSits: 32,
          callsToSales: 22,
          apPerCall: 65,
          contactToSales: 25,
          apPerContact: 75,
          scheduledToSits: 80,
          sitsToSales: 67,
          apPerSit: 200,
          apPerSale: 300,
        },
      },
    },
    {
      name: "Jordan Hayes",
      role: "Agent",
      metrics: {
        leads: 41,
        calls: 35,
        contacts: 30,
        scheduled: 14,
        sits: 11,
        sales: 7,
        ap: 2100,
        conversion: 64,
        ratios: {
          leadToContact: 73,
          leadToScheduled: 34,
          leadToSits: 27,
          leadToSales: 17,
          apPerLead: 51,
          contactToScheduled: 47,
          contactToSits: 37,
          callsToContact: 86,
          callsToScheduled: 40,
          callsToSits: 31,
          callsToSales: 20,
          apPerCall: 60,
          contactToSales: 23,
          apPerContact: 70,
          scheduledToSits: 79,
          sitsToSales: 64,
          apPerSit: 191,
          apPerSale: 300,
        },
      },
    },
    {
      name: "Cameron Ross",
      role: "Agent",
      metrics: {
        leads: 42,
        calls: 36,
        contacts: 31,
        scheduled: 14,
        sits: 11,
        sales: 7,
        ap: 2100,
        conversion: 64,
        ratios: {
          leadToContact: 74,
          leadToScheduled: 33,
          leadToSits: 26,
          leadToSales: 17,
          apPerLead: 50,
          contactToScheduled: 45,
          contactToSits: 35,
          callsToContact: 86,
          callsToScheduled: 39,
          callsToSits: 31,
          callsToSales: 19,
          apPerCall: 58,
          contactToSales: 23,
          apPerContact: 68,
          scheduledToSits: 79,
          sitsToSales: 64,
          apPerSit: 191,
          apPerSale: 300,
        },
      },
    },
    {
      name: "Morgan Silva",
      role: "Agent",
      metrics: {
        leads: 45,
        calls: 38,
        contacts: 32,
        scheduled: 15,
        sits: 12,
        sales: 8,
        ap: 2400,
        conversion: 67,
        ratios: {
          leadToContact: 71,
          leadToScheduled: 33,
          leadToSits: 27,
          leadToSales: 18,
          apPerLead: 53,
          contactToScheduled: 47,
          contactToSits: 38,
          callsToContact: 84,
          callsToScheduled: 39,
          callsToSits: 32,
          callsToSales: 21,
          apPerCall: 63,
          contactToSales: 25,
          apPerContact: 75,
          scheduledToSits: 80,
          sitsToSales: 67,
          apPerSit: 200,
          apPerSale: 300,
        },
      },
    },
    {
      name: "Taylor Reed",
      role: "Agent",
      metrics: {
        leads: 43,
        calls: 37,
        contacts: 31,
        scheduled: 14,
        sits: 11,
        sales: 7,
        ap: 2100,
        conversion: 63,
        ratios: {
          leadToContact: 72,
          leadToScheduled: 33,
          leadToSits: 26,
          leadToSales: 16,
          apPerLead: 49,
          contactToScheduled: 45,
          contactToSits: 35,
          callsToContact: 84,
          callsToScheduled: 38,
          callsToSits: 30,
          callsToSales: 19,
          apPerCall: 57,
          contactToSales: 23,
          apPerContact: 68,
          scheduledToSits: 79,
          sitsToSales: 64,
          apPerSit: 191,
          apPerSale: 300,
        },
      },
    },
  ],
  "Iota Team": [
    {
      name: "Samuel Park",
      role: "Manager",
      metrics: {
        leads: 47,
        calls: 40,
        contacts: 34,
        scheduled: 16,
        sits: 13,
        sales: 9,
        ap: 2700,
        conversion: 69,
        ratios: {
          leadToContact: 72,
          leadToScheduled: 34,
          leadToSits: 28,
          leadToSales: 19,
          apPerLead: 57,
          contactToScheduled: 47,
          contactToSits: 38,
          callsToContact: 85,
          callsToScheduled: 40,
          callsToSits: 33,
          callsToSales: 23,
          apPerCall: 68,
          contactToSales: 26,
          apPerContact: 79,
          scheduledToSits: 81,
          sitsToSales: 69,
          apPerSit: 208,
          apPerSale: 300,
        },
      },
    },
    {
      name: "Riley Morgan",
      role: "Agent",
      metrics: {
        leads: 42,
        calls: 36,
        contacts: 31,
        scheduled: 14,
        sits: 11,
        sales: 7,
        ap: 2100,
        conversion: 64,
        ratios: {
          leadToContact: 74,
          leadToScheduled: 33,
          leadToSits: 26,
          leadToSales: 17,
          apPerLead: 50,
          contactToScheduled: 45,
          contactToSits: 35,
          callsToContact: 86,
          callsToScheduled: 39,
          callsToSits: 31,
          callsToSales: 19,
          apPerCall: 58,
          contactToSales: 23,
          apPerContact: 68,
          scheduledToSits: 79,
          sitsToSales: 64,
          apPerSit: 191,
          apPerSale: 300,
        },
      },
    },
    {
      name: "Casey Zhang",
      role: "Agent",
      metrics: {
        leads: 44,
        calls: 37,
        contacts: 32,
        scheduled: 15,
        sits: 12,
        sales: 8,
        ap: 2400,
        conversion: 67,
        ratios: {
          leadToContact: 73,
          leadToScheduled: 34,
          leadToSits: 27,
          leadToSales: 18,
          apPerLead: 55,
          contactToScheduled: 47,
          contactToSits: 38,
          callsToContact: 86,
          callsToScheduled: 41,
          callsToSits: 32,
          callsToSales: 22,
          apPerCall: 65,
          contactToSales: 25,
          apPerContact: 75,
          scheduledToSits: 80,
          sitsToSales: 67,
          apPerSit: 200,
          apPerSale: 300,
        },
      },
    },
    {
      name: "Drew Campbell",
      role: "Agent",
      metrics: {
        leads: 43,
        calls: 36,
        contacts: 31,
        scheduled: 14,
        sits: 11,
        sales: 7,
        ap: 2100,
        conversion: 65,
        ratios: {
          leadToContact: 72,
          leadToScheduled: 33,
          leadToSits: 26,
          leadToSales: 16,
          apPerLead: 49,
          contactToScheduled: 45,
          contactToSits: 35,
          callsToContact: 86,
          callsToScheduled: 39,
          callsToSits: 31,
          callsToSales: 19,
          apPerCall: 58,
          contactToSales: 23,
          apPerContact: 68,
          scheduledToSits: 79,
          sitsToSales: 64,
          apPerSit: 191,
          apPerSale: 300,
        },
      },
    },
    {
      name: "Avery Nguyen",
      role: "Agent",
      metrics: {
        leads: 41,
        calls: 35,
        contacts: 30,
        scheduled: 14,
        sits: 11,
        sales: 7,
        ap: 2100,
        conversion: 63,
        ratios: {
          leadToContact: 73,
          leadToScheduled: 34,
          leadToSits: 27,
          leadToSales: 17,
          apPerLead: 51,
          contactToScheduled: 47,
          contactToSits: 37,
          callsToContact: 86,
          callsToScheduled: 40,
          callsToSits: 31,
          callsToSales: 20,
          apPerCall: 60,
          contactToSales: 23,
          apPerContact: 70,
          scheduledToSits: 79,
          sitsToSales: 64,
          apPerSit: 191,
          apPerSale: 300,
        },
      },
    },
    {
      name: "Jamie Collins",
      role: "Agent",
      metrics: {
        leads: 45,
        calls: 38,
        contacts: 32,
        scheduled: 15,
        sits: 12,
        sales: 8,
        ap: 2400,
        conversion: 67,
        ratios: {
          leadToContact: 71,
          leadToScheduled: 33,
          leadToSits: 27,
          leadToSales: 18,
          apPerLead: 53,
          contactToScheduled: 47,
          contactToSits: 38,
          callsToContact: 84,
          callsToScheduled: 39,
          callsToSits: 32,
          callsToSales: 21,
          apPerCall: 63,
          contactToSales: 25,
          apPerContact: 75,
          scheduledToSits: 80,
          sitsToSales: 67,
          apPerSit: 200,
          apPerSale: 300,
        },
      },
    },
  ],
};
